---
title: "Begrazing Schapen Analyse"
author: "Femke Batsleer"
date: "8 April 2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggsignif)
library(ggsci)
library(effects)
library(afex)
library(lme4)
library(sjPlot)
```

# Read data

```{r}
#read data
rd <- read.csv(file="data_grazing_BACI.csv", header=T, sep=";")

#rename data and get in right format
rd_tidy <- rd %>%
  mutate(Site = ifelse(Site=="Cabour", "Site1",
                       ifelse(Site=="Controle thesis", "Control", "Site2"))) %>%
  rename(Timepoint=Meetpunt, Year=Jaar) %>%
  mutate(Site = as.factor(Site)) %>%
  mutate(Year=as.factor(Year))

rd_tidy$Datum <- factor(rd_tidy$Datum, levels=unique(rd$Datum))
rd_tidy$Date <- as.Date(rd_tidy$Datum, format="%d/%m/%Y")

rd_tidy <- rd_tidy %>% 
  rename(nClosedNests = Aantal.toe,
         nOpenNests = Aantal.open)
rd_tidy <- rd_tidy %>% mutate(PlotUnique = paste0(Site, as.character(Plot)))

head(rd_tidy)
summary(rd_tidy)
nrow(rd_tidy)
```

# Statistical model

```{r}
#running statistical model
model_closed <- glmer.nb(nClosedNests ~ Year +
                           Site +
                           Year:Site +
                           (1 | PlotUnique) +
                           (1 | Timepoint),
                    data = rd_tidy,
                    control = glmerControl(optimizer = "bobyqa",
                    optCtrl = list(maxfun = 2e5)))
summary(model_closed)

plot_model(model_closed,
           type = "pred",
           terms = c("Year", "Site"),
           dot.size = 3,
           line.size = 1) +
  xlab("Site") +
  ylab("Number of nests") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1),
        axis.text = element_text(size = 20),
        axis.title = element_text(size = 25,
                                  face = "bold"),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20), 
        panel.background = element_rect(fill = "white",
                                        colour = "grey",
                                        size = 1,
                                        linetype = "solid"), 
        panel.grid.major = element_line(size = 0.5,
                                        linetype = "solid",
                                        colour = "grey")) +
  scale_colour_jco()


plot_model(model_closed,
           type = "pred",
           terms = c("Site", "Year"),
           dot.size = 3,
           line.size = 1) +
  xlab("Site") +
  ylab("Number of nests") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1),
        axis.text = element_text(size = 20),
        axis.title = element_text(size = 25,
                                  face = "bold"),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20), 
        panel.background = element_rect(fill = "white",
                                        colour = "grey",
                                        size = 1,
                                        linetype = "solid"), 
        panel.grid.major = element_line(size = 0.5,
                                        linetype = "solid",
                                        colour = "grey")) +
  scale_colour_jco()
```

# Plots

To plot the graphs, the average over the different plots is taken (random effect in model)

```{r}
#Summarize to get average over plots per level of grazing 
rd_tidy_summary <- rd_tidy %>% ungroup() %>%
  # mutate(Site=recode_factor(Site, "Controle thesis"="Controle",
  #                           "Cabour" = "Extensief",
  #                           "Westhoek Zuid" = "Stoot")) %>%
  group_by(Year, Site) %>%
  summarise(avg.closed = mean(nClosedNests), sd.closed = sd(nClosedNests),
            avg.open = mean(nOpenNests), sd.open = sd(nOpenNests),
            n=n()) %>%
  mutate(se.closed=sd.closed/sqrt(n),
         se.open = sd.open/sqrt(n))


barplot_closed_year <- ggplot(rd_tidy_summary, aes(x=Year, y=avg.closed, fill=Site))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(aes(ymin=avg.closed-se.closed, ymax=avg.closed+se.closed), width=.2, position=position_dodge(0.9))+
  scale_fill_manual(values=c("#deebf7", "#9ecae1", "#3182bd"))+
  theme(panel.background = element_blank())+
  theme(panel.grid.major.y = element_line(colour = "grey90"))+
  theme(axis.line = element_line(colour = "grey50"))+
  theme(text=element_text(size=16))+
  #ggtitle("Closed nests (reproduction)") +
  ylab("Number of nests")+xlab("Year") +
  ylim(c(-1.4,50))+
  guides(fill=guide_legend(title="Site"), linetype=guide_legend(title="Site"))
barplot_closed_year

barplot_closed_site <- ggplot(rd_tidy_summary, aes(x=Site, y=avg.closed, fill=Year))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(aes(ymin=avg.closed-se.closed, ymax=avg.closed+se.closed), width=.2, position=position_dodge(0.9))+ 
  scale_fill_brewer(palette="Blues")+
  theme_bw()+
  theme(text=element_text(size=16))+
  #ggtitle("Closed nests (reproduction)") +
  ylab("Number of nests")+xlab("Site") +
  guides(fill=guide_legend(title="Year"))
barplot_closed_site
```

# Relative/proportion plots

```{r}
rd_tidy_prop <- rd_tidy_summary %>% dplyr::select(-avg.open, -sd.open, -se.open) %>%
  pivot_wider(names_from= Site, values_from=c(avg.closed, sd.closed, n, se.closed)) %>%
  mutate(prop_avg.closed_Site1 =  (avg.closed_Site1)/avg.closed_Control,
         prop_avg.closed_Site2 =  (avg.closed_Site2)/avg.closed_Control) %>%
  mutate(prop_se.closed_Site1 = prop_avg.closed_Site1*(sqrt((se.closed_Site1/avg.closed_Site1)^2 + (se.closed_Control/avg.closed_Control)^2)),
         prop_se.closed_Site2 = prop_avg.closed_Site2*(sqrt((se.closed_Site2/avg.closed_Site2)^2 + (se.closed_Control/avg.closed_Control)^2))) %>%
  dplyr::select(Year, prop_avg.closed_Site1, prop_avg.closed_Site2,
                prop_se.closed_Site1, prop_se.closed_Site2)

rd_tidy_prop_avg <- rd_tidy_prop %>% dplyr::select(Year, prop_avg.closed_Site1, prop_avg.closed_Site2) %>%
  rename(Site1=prop_avg.closed_Site1, Site2=prop_avg.closed_Site2) %>%
  pivot_longer(c(Site1, Site2), names_to="Site", values_to="prop.avg_closed")
rd_tidy_prop_se <- rd_tidy_prop %>% dplyr::select(Year, prop_se.closed_Site1, prop_se.closed_Site2) %>%
  rename(Site1=prop_se.closed_Site1, Site2=prop_se.closed_Site2) %>%
  pivot_longer(c(Site1, Site2), names_to="Site", values_to="prop.se_closed")

rd_tidy_prop <- rd_tidy_prop_avg %>% full_join(rd_tidy_prop_se, by=c("Year", "Site")) %>% ungroup()

rd_tidy_prop <- rd_tidy_prop %>%
  add_row(Year="2018", Site="Control", prop.avg_closed=0, prop.se_closed=NA) %>%
  add_row(Year="2019", Site="Control", prop.avg_closed=0, prop.se_closed=NA) %>%
  add_row(Year="2020", Site="Control", prop.avg_closed=0, prop.se_closed=NA)

head(rd_tidy_prop)

barplot_prop_year <- ggplot(rd_tidy_prop, aes(x=Year, y=prop.avg_closed))+
  geom_bar(stat="identity", position=position_dodge(), aes(fill=Site))+
  geom_errorbar(aes(ymin=prop.avg_closed-prop.se_closed, ymax=prop.avg_closed+prop.se_closed,
                    fill=Site), width=.2, position=position_dodge(0.9))+
  geom_signif(stat="identity",
              data=data.frame(x=c(1, 1.3, 1, 1.3),
                              xend=c(2, 2.3, 3, 3.3),
                              y=c(1.22,0.95, 1.32,1.05),
                              annotation=c("ns", "***","**", " ***"),
                              Site=c("Site1", "Site2", "Site1", "Site2")),
              aes(x=x,xend=xend, y=y, yend=y,annotation=annotation, col=Site, textsize=8, vjust=0.15), size=5, show.legend=F)+
  scale_fill_manual(values=c("#deebf7", "#9ecae1", "#3182bd"))+
  scale_color_manual(values=c("#9ecae1", "#3182bd"))+
  theme(panel.background = element_blank())+
  theme(panel.grid.major.y = element_line(colour = "grey90"))+
  theme(axis.line = element_line(colour = "grey50"))+
  ylim(c(-0.05,1.4))+
  theme(text=element_text(size=16))+
  #ggtitle("Closed nests (reproduction)") +
  ylab("Proportion of nests compared to Control")+xlab("Year") +
  guides(fill=guide_legend(title="Site"))
barplot_prop_year
```

